# Custom data for person detection


# train and val data as 1) directory: path/images/, 2) file: path/images.txt, or 3) list: [path1/images/, path2/images/]
train: dataset/person_count/images/train
val: dataset/person_count_val/images/train

# number of classes
nc: 6

# class names
names: ['full-faced',
'half-faced',
'helmetRider',
'invalid',
'no-helmet',
'noHelmetRider']
